name: CI-CD-Pipeline

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24]

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      # Frontend Dependencies
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install


  security-check:

    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget gnupg

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
          gpg --dearmor | \
          sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | \
          sudo tee /etc/apt/sources.list.d/trivy.list

          sudo apt-get update -y
          sudo apt-get install -y trivy

      # Trivy Scan
      - name: Trivy File System Scan
        run: |
          trivy fs --format table -o fs-report.json .

      # Install Gitleaks
      - name: Install Gitleaks
        run: |
          sudo apt update -y
          sudo apt install -y gitleaks

      # Gitleaks Scan
      - name: Gitleaks Code Scan
        run: |
          gitleaks detect source . -r gitleaks-report.json -f json


  build_docker_image_and_push:

    runs-on: ubuntu-latest
    needs: security-check

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      # DockerHub Login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Setup QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Setup Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Backend Image
      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: aravind2003/fullstack-backend:latest
          file: ./backend/Dockerfile

      # Build Frontend Image
      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: aravind2003/fullstack-frontend:latest
          file: ./frontend/Dockerfile


  deploy_to_kubernetes:

    runs-on: self-hosted
    needs: build_docker_image_and_push

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Verify AWS CLI
      - name: Verify AWS CLI
        run: |
          aws --version

      # Verify kubectl
      - name: Verify kubectl
        run: |
          kubectl version --client

      # Configure kubeconfig for EKS
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name devopsshack-cluster

      # Verify Kubernetes Cluster
      - name: Verify Kubernetes Cluster
        run: |
          kubectl get nodes

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ds.yml
